### ISSUE TITLE
Bug / Crash: NPE near "nodeHash"

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec#18]
Application: io.oversec.one
Version: 1005005
Build-Type: release
Flavor: oversec
Android-Version: 27
Android-Build: oneplus/bacon/A0001:6.0.1/MHC19Q/ZNH2KAS1KN:user/release-keys
Hardware: oneplus/OnePlus / A0001 / bacon
Open-Keychain-Version: 52009
Thread: main
Stacktrace:
java.lang.NullPointerException: Attempt to read from field 'int io.oversec.one.acs.NodeAndFlag.nodeHash' on a null object reference
at io.oversec.one.acs.OversecAccessibilityService.sendScrapeSubtreeMessage$1f330bf7(OversecAccessibilityService.java:567)
at io.oversec.one.acs.OversecAccessibilityService.sendScrapeSubtreeMessages(OversecAccessibilityService.java:548)
at io.oversec.one.acs.OversecAccessibilityService.onAccessibilityEvent(OversecAccessibilityService.java:515)
at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1524)
at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1710)
at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by oversecio** [comment]
another one:

Application: io.oversec.one
Version: 1005005
Build-Type: release
Flavor: oversec
Android-Version: 26
Android-Build: Verizon/heroqltevzw/heroqltevzw:8.0.0/R16NW/G930VVRS8CRK2:user/release-keys
Hardware: Verizon/samsung / SM-G930V / heroqltevzw
Open-Keychain-Version: 52009
-------------------------
Thread: main
Stacktrace:
java.lang.NullPointerException: Attempt to read from field 'int io.oversec.one.acs.NodeAndFlag.nodeHash' on a null object reference
at io.oversec.one.acs.OversecAccessibilityService.sendRefreshNodeMessage(OversecAccessibilityService.java:613)
at io.oversec.one.acs.OversecAccessibilityService.sendRefreshNodeMessages(OversecAccessibilityService.java:586)
at io.oversec.one.acs.OversecAccessibilityService.onAccessibilityEvent(OversecAccessibilityService.java:480)
at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1550)
at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1735)
at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by oversecio** [comment]
one more:

Application: io.oversec.one
Version: 1005009
Build-Type: release
Flavor: oversec
Android-Version: 23
Android-Build: Fairphone/FP2/FP2:6.0.1/FP2-gms-18.04.1/FP2-gms-18.04.1:user/release-keys
Hardware: Fairphone/Fairphone / FP2 / FP2
Open-Keychain-Version: 52009
-------------------------
Thread: main
Stacktrace:
java.lang.NullPointerException: Attempt to read from field 'int io.oversec.one.acs.NodeAndFlag.nodeHash' on a null object reference
at io.oversec.one.acs.OversecAccessibilityService.sendRefreshNodeMessage(OversecAccessibilityService.java:617)
at io.oversec.one.acs.OversecAccessibilityService.sendRefreshNodeMessages(OversecAccessibilityService.java:590)
at io.oversec.one.acs.OversecAccessibilityService.onAccessibilityEvent(OversecAccessibilityService.java:480)
at android.accessibilityservice.AccessibilityService$1.onAccessibilityEvent(AccessibilityService.java:658)
at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:751)
at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

LOGCAT:
--------- beginning of main
05-04 13:03:08.864 4215 4215 D AndroidRuntime: Shutting down VM
05-04 13:03:08.867 4215 4215 I System.out: ********************* CRASH ******************* 
05-04 13:03:08.867 4215 4215 W System.err: java.lang.NullPointerException: Attempt to read from field 'int io.oversec.one.acs.NodeAndFlag.nodeHash' on a null object reference
05-04 13:03:08.878 4215 4215 W System.err: at io.oversec.one.acs.OversecAccessibilityService.sendRefreshNodeMessage(OversecAccessibilityService.java:617)
05-04 13:03:08.878 4215 4215 W System.err: at io.oversec.one.acs.OversecAccessibilityService.sendRefreshNodeMessages(OversecAccessibilityService.java:590)
05-04 13:03:08.878 4215 4215 W System.err: at io.oversec.one.acs.OversecAccessibilityService.onAccessibilityEvent(OversecAccessibilityService.java:480)
05-04 13:03:08.878 4215 4215 W System.err: at android.accessibilityservice.AccessibilityService$1.onAccessibilityEvent(AccessibilityService.java:658)
05-04 13:03:08.878 4215 4215 W System.err: at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:751)
05-04 13:03:08.879 4215 4215 W System.err: at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
05-04 13:03:08.879 4215 4215 W System.err: at android.os.Handler.dispatchMessage(Handler.java:102)
05-04 13:03:08.879 4215 4215 W System.err: at android.os.Looper.loop(Looper.java:148)
05-04 13:03:08.879 4215 4215 W System.err: at android.app.ActivityThread.main(ActivityThread.java:5417)
05-04 13:03:08.879 4215 4215 W System.err: at java.lang.reflect.Method.invoke(Native Method)
05-04 13:03:08.879 4215 4215 W System.err: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-04 13:03:08.879 4215 4215 W System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
