### ISSUE TITLE
Bug / Crash: IllegalArgumentException near "onEditorAction"

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec#19]
Application: io.oversec.one
Version: 1005005
Build-Type: release
Flavor: oversec
Android-Version: 26
Android-Build: samsung/hero2ltexx/hero2lte:8.0.0/R16NW/G935FXXS3ERL1:user/release-keys
Hardware: samsung/samsung / SM-G935F / hero2ltexx
Open-Keychain-Version: 52009
Thread: main
Stacktrace:
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method io.oversec.one.crypto.sym.ui.UnlockKeyActivity$PassphraseDialogFragment.onEditorAction, parameter event
at io.oversec.one.crypto.sym.ui.UnlockKeyActivity$PassphraseDialogFragment.onEditorAction(Unknown Source:7)
at android.widget.TextView.onEditorAction(TextView.java:6605)
at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:360)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by oversecio** [comment]
fixed via https://github.com/oversecio/oversec_crypto/commit/c79730cdaf6098a6f9da4d5084138aa5f5e11efa
