### ISSUE TITLE
Crash "lateinit property mView has not been initialized"

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec#54]
Application: io.oversec.one
Version: 1005013
Build-Type: release
Flavor: oversec
Android-Version: 26
Android-Build: lge/elsa_spr_us/elsa:8.0.0/OPR1.170623.032/1819814314eb7:user/release-keys
Hardware: lge/LGE / LG-LS997 / elsa_spr_us
Open-Keychain-Version: 52009
-------------------------
Thread: main
Stacktrace:
java.lang.RuntimeException: Unable to resume activity {io.oversec.one/io.oversec.one.ui.EncryptionParamsActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=6003, result=-1, data=Intent { act=org.openintents.openpgp.action.ENCRYPT (has extras) }} to activity {io.oversec.one/io.oversec.one.ui.EncryptionParamsActivity}: kotlin.UninitializedPropertyAccessException: lateinit property mView has not been initialized
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3715)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3755)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2939)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6710)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=6003, result=-1, data=Intent { act=org.openintents.openpgp.action.ENCRYPT (has extras) }} to activity {io.oversec.one/io.oversec.one.ui.EncryptionParamsActivity}: kotlin.UninitializedPropertyAccessException: lateinit property mView has not been initialized
at android.app.ActivityThread.deliverResults(ActivityThread.java:4398)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3687)
... 10 more
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property mView has not been initialized
at io.oversec.one.crypto.ui.AbstractEncryptionParamsFragment.getMView(AbstractEncryptionParamsFragment.kt:16)
at io.oversec.one.ui.encparams.GpgEncryptionParamsFragment.onActivityResult(GpgEncryptionParamsFragment.java:393)
at io.oversec.one.ui.EncryptionParamsActivity.onActivityResult(EncryptionParamsActivity.java:472)
at android.app.Activity.dispatchActivityResult(Activity.java:7240)
at android.app.ActivityThread.deliverResults(ActivityThread.java:4394)
... 11 more

**Comment by oversecio** [comment]
fixed
